services:
    _defaults:
      autowire: true
      autoconfigure: true            
    
    App\User\Adapter\:
        resource: '../../src/User/Adapter'
        tags: [ 'controller.service_arguments' ]

    App\User\Application\:
        resource: '../../src/User/Application/'

    App\User\Adapter\Database\ORM\Doctrine\Repository:
        tags: ['doctrine.repository_service']

    App\User\Domain\:
        resource: '../../src/User/Domain/'

    App\User\Adapter\Command\UserCreate:
        class: App\User\Adapter\Command\UserCreate\userCreateCommand
        tags: ['console.command']
    
    App\User\Adapter\Command\UserDelete:
        class: App\User\Adapter\Command\UserDelete\userDeleteCommand
        tags: ['console.command']

    App\User\Adapter\Security\JWT:
        class: App\User\Adapter\Security\JWT\onCreatedUserAuthentication
        tags:
            - { name: kernel.event_listener, event: lexik_jwt_authentication.on_authentication_success, method: onAuthenticationSuccessResponse }