doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'

        # IMPORTANT: You MUST configure your server version,
        # either here or in the DATABASE_URL env var (see .env file)
        #server_version: '13'
    orm:
        auto_generate_proxy_classes: true
        default_entity_manager: Library
        entity_managers:
            Movie:                
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Movie:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Movie/Adapter/Database/ORM/Doctrine/Mapping'
                        prefix: 'App\Movie\Domain\Model'
                        alias: Movie
            MovieMeta:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    MovieMeta:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Movie/Adapter/Database/ORM/Doctrine/Mapping'
                        prefix: 'App\Movie\Domain\Model'
                        alias: MovieMeta
            Library:
                naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
                mappings:
                    Library:
                        is_bundle: false
                        type: xml
                        dir: '%kernel.project_dir%/src/Library/Adapter/Database/ORM/Doctrine/Mapping'
                        prefix: 'App\Library\Domain\Model'
                        alias: Library
when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
