createMovies:
    path:       /create
    controller: App\Movie\Adapter\createMovieController
    methods:    POST

getMovie:
    path:       /{uuid}
    controller: App\Movie\Adapter\getMovieController
    methods:    GET


getMoviesLibrary:
    path:       /{uuid}/library
    controller: App\Movie\Adapter\getMoviesLibraryController
    methods:    GET
